version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=resto

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=resto
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 